use_frameworks!

target 'TsgsSelector_Example' do
  pod 'TsgsSelector', :path => '../'

  target 'TsgsSelector_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
