use_frameworks!

target 'TsgsSelector_Example' do
  pod 'TsgsSelector', :path => '../'

  target 'TsgsSelector_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.0.0'
    pod 'Nimble', '~> 8.0.0'
  end
end
